// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface A98rgbSpace extends ColorSpace {
	name: 'a98rgb';
}

declare const a98rgb: A98rgbSpace;
export default a98rgb;
