// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface AcescgSpace extends ColorSpace {
	name: 'acescg';
}

declare const acescg: AcescgSpace;
export default acescg;
