// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface AcesproxySpace extends ColorSpace {
	name: 'acesproxy';
	range: [[0.0626, 0.9189], [0.0626, 0.9189], [0.0626, 0.9189]];
}

declare const acesproxy: AcesproxySpace;
export default acesproxy;
