// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface AcescgSpace extends ColorSpace {
	name: 'acescg';
	range: [[0, 65504], [0, 65504], [0, 65504]];
}

declare const acescg: AcescgSpace;
export default acescg;
