// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface AcesccSpace extends ColorSpace {
	name: 'acescc';
}

declare const acescc: AcesccSpace;
export default acescc;
