// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface AcescctSpace extends ColorSpace {
	name: 'acescct';
	range: [[-0.358, 1.468], [-0.358, 1.468], [-0.358, 1.468]];
}

declare const acescct: AcescctSpace;
export default acescct;
