// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface Aces2065_1Space extends ColorSpace {
	name: 'aces2065-1';
}

declare const aces2065_1: Aces2065_1Space;
export default aces2065_1;
