// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface AcesccSpace extends ColorSpace {
	name: 'acescc';
	range: [[-0.35828683, 1.4679963120447153], [-0.35828683, 1.4679963120447153], [-0.35828683, 1.4679963120447153]];
}

declare const acescc: AcesccSpace;
export default acescc;
