// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface AcesproxySpace extends ColorSpace {
	name: 'acesproxy';
	range: [[0.06256109481915934, 0.9188660801564027], [0.06256109481915934, 0.9188660801564027], [0.06256109481915934, 0.9188660801564027]];
}

declare const acesproxy: AcesproxySpace;
export default acesproxy;
