// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface AcescctSpace extends ColorSpace {
	name: 'acescct';
}

declare const acescct: AcescctSpace;
export default acescct;
