// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface AnlabSpace extends ColorSpace {
	name: 'anlab';
}

declare const anlab: AnlabSpace;
export default anlab;
