// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface AnlabSpace extends ColorSpace {
	name: 'anlab';
	range: [[0, 100], [-100, 100], [-100, 100]];
}

declare const anlab: AnlabSpace;
export default anlab;
