// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface Apple_rgbSpace extends ColorSpace {
	name: 'apple-rgb';
	range: [[0, 1], [0, 1], [0, 1]];
}

declare const apple_rgb: Apple_rgbSpace;
export default apple_rgb;
