// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface ApplelogSpace extends ColorSpace {
	name: 'applelog';
	range: [[0, 1], [0, 1], [0, 1]];
}

declare const applelog: ApplelogSpace;
export default applelog;
