// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface Atd95Space extends ColorSpace {
	name: 'atd95';
	range: [[0, 0.05], [-0.01, 0.08], [-0.03, 0.06]];
}

declare const atd95: Atd95Space;
export default atd95;
