// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface BmdfilmSpace extends ColorSpace {
	name: 'bmdfilm';
	range: [[0, 1], [0, 1], [0, 1]];
}

declare const bmdfilm: BmdfilmSpace;
export default bmdfilm;
