// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface Cam02_ucsSpace extends ColorSpace {
	name: 'cam02-ucs';
	range: [[0, 100], [-50, 50], [-50, 50]];
}

declare const cam02_ucs: Cam02_ucsSpace;
export default cam02_ucs;
