// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface Cam02_lcdSpace extends ColorSpace {
	name: 'cam02-lcd';
	range: [[0, 100], [-50, 50], [-50, 50]];
}

declare const cam02_lcd: Cam02_lcdSpace;
export default cam02_lcd;
