// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface Cam02_scdSpace extends ColorSpace {
	name: 'cam02-scd';
	range: [[0, 100], [-50, 50], [-50, 50]];
}

declare const cam02_scd: Cam02_scdSpace;
export default cam02_scd;
