// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface Cam16_ucsSpace extends ColorSpace {
	name: 'cam16-ucs';
	range: [[0, 100], [-50, 50], [-50, 50]];
}

declare const cam16_ucs: Cam16_ucsSpace;
export default cam16_ucs;
