// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface Cam16Space extends ColorSpace {
	name: 'cam16';
	range: [[0, 100], [0, 105], [0, 360]];
}

declare const cam16: Cam16Space;
export default cam16;
