// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface Cam16_lcdSpace extends ColorSpace {
	name: 'cam16-lcd';
	range: [[0, 100], [-50, 50], [-50, 50]];
}

declare const cam16_lcd: Cam16_lcdSpace;
export default cam16_lcd;
