// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface Cam16_scdSpace extends ColorSpace {
	name: 'cam16-scd';
	range: [[0, 100], [-50, 50], [-50, 50]];
}

declare const cam16_scd: Cam16_scdSpace;
export default cam16_scd;
