// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface Cie_rgbSpace extends ColorSpace {
	name: 'cie-rgb';
	range: [[0, 1], [0, 1], [0, 1]];
}

declare const cie_rgb: Cie_rgbSpace;
export default cie_rgb;
