// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface Ciecam02Space extends ColorSpace {
	name: 'ciecam02';
	range: [[0, 100], [0, 100], [0, 360]];
}

declare const ciecam02: Ciecam02Space;
export default ciecam02;
