// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface CineonSpace extends ColorSpace {
	name: 'cineon';
	range: [[0, 1], [0, 1], [0, 1]];
}

declare const cineon: CineonSpace;
export default cineon;
