// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface Clog3Space extends ColorSpace {
	name: 'clog3';
	range: [[0, 1], [0, 1], [0, 1]];
}

declare const clog3: Clog3Space;
export default clog3;
