// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface ClogSpace extends ColorSpace {
	name: 'clog';
	range: [[0, 1], [0, 1], [0, 1]];
}

declare const clog: ClogSpace;
export default clog;
