// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface Clog2Space extends ColorSpace {
	name: 'clog2';
	range: [[0, 1], [0, 1], [0, 1]];
}

declare const clog2: Clog2Space;
export default clog2;
