// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface CmySpace extends ColorSpace {
	name: 'cmy';
	range: [[0, 100], [0, 100], [0, 100]];
}

declare const cmy: CmySpace;
export default cmy;
