// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface CmykSpace extends ColorSpace {
	name: 'cmyk';
	range: [[0, 100], [0, 100], [0, 100], [0, 100]];
}

declare const cmyk: CmykSpace;
export default cmyk;
