// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface ColoroidSpace extends ColorSpace {
	name: 'coloroid';
}

declare const coloroid: ColoroidSpace;
export default coloroid;
