// Generated by scripts/generate-types.js — do not edit by hand

/** Convert one space's channel values to another space: e.g. `rgb.lab(255, 0, 0)`. */
export type Convert = (...channels: number[]) => number[];

/** A color space: its id, conventional channel `range`, and converters to every other space. */
export interface ColorSpace {
	/** space id, e.g. 'rgb' */
	name: string;
	/** conventional channel ranges, e.g. [[0, 255], [0, 255], [0, 255]] */
	range?: ReadonlyArray<readonly [number, number]>;
	/** converter to another space, keyed by its name — `space.rgb.lab(255, 0, 0)` */
	[to: string]: any;
}
