// Generated by scripts/generate-types.js — do not edit by hand

/**
 * Convert one space's values to another space, in either calling form:
 * scalar — `rgb.lab(255, 0, 0)` → `number[]`; batch — an interleaved
 * array-like of pixels (stride = the space's channel count) → a new
 * `Float64Array`: `rgb.lab([255, 0, 0, 0, 128, 255])`. Trailing params
 * (e.g. ycbcr's kb, kr) follow the channels / the pixel array.
 */
export type Convert = {
	(...channels: number[]): number[];
	(pixels: ArrayLike<number>, ...params: number[]): Float64Array;
};

/** A color space: its id, conventional channel `range`, and converters to every other space. */
export interface ColorSpace {
	/** space id, e.g. 'rgb' */
	name: string;
	/** conventional channel ranges, e.g. [[0, 255], [0, 255], [0, 255]] */
	range?: ReadonlyArray<readonly [number, number]>;
	/** converter to another space, keyed by its name — `space.rgb.lab(255, 0, 0)` */
	[to: string]: any;
}
