// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface CubehelixSpace extends ColorSpace {
	name: 'cubehelix';
	range: [[0, 1]];
}

declare const cubehelix: CubehelixSpace;
export default cubehelix;
