// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface DavinciSpace extends ColorSpace {
	name: 'davinci';
	range: [[0, 1], [0, 1], [0, 1]];
}

declare const davinci: DavinciSpace;
export default davinci;
