// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface Dci_p3Space extends ColorSpace {
	name: 'dci-p3';
	range: [[0, 1], [0, 1], [0, 1]];
}

declare const dci_p3: Dci_p3Space;
export default dci_p3;
