// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface Din99dSpace extends ColorSpace {
	name: 'din99d';
	range: [[0, 100], [-50, 50], [-50, 50]];
}

declare const din99d: Din99dSpace;
export default din99d;
