// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface Din99o_lchSpace extends ColorSpace {
	name: 'din99o-lch';
	range: [[0, 100], [0, 51.484], [0, 360]];
}

declare const din99o_lch: Din99o_lchSpace;
export default din99o_lch;
