// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface Din99o_labSpace extends ColorSpace {
	name: 'din99o-lab';
	range: [[0, 100], [-40.09, 45.501], [-40.469, 44.344]];
}

declare const din99o_lab: Din99o_labSpace;
export default din99o_lab;
