// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface DklSpace extends ColorSpace {
	name: 'dkl';
	range: [[-100, 0], [-31, 0], [0, 99]];
}

declare const dkl: DklSpace;
export default dkl;
