// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface DlogSpace extends ColorSpace {
	name: 'dlog';
	range: [[0, 1], [0, 1], [0, 1]];
}

declare const dlog: DlogSpace;
export default dlog;
