// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface DshSpace extends ColorSpace {
	name: 'dsh';
}

declare const dsh: DshSpace;
export default dsh;
