// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface ErimmSpace extends ColorSpace {
	name: 'erimm';
	range: [[0, 1], [0, 1], [0, 1]];
}

declare const erimm: ErimmSpace;
export default erimm;
