// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface FilmicproSpace extends ColorSpace {
	name: 'filmicpro';
	range: [[0, 1], [0, 1], [0, 1]];
}

declare const filmicpro: FilmicproSpace;
export default filmicpro;
