// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface FlogSpace extends ColorSpace {
	name: 'flog';
	range: [[0, 1], [0, 1], [0, 1]];
}

declare const flog: FlogSpace;
export default flog;
