// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface Flog2Space extends ColorSpace {
	name: 'flog2';
	range: [[0, 1], [0, 1], [0, 1]];
}

declare const flog2: Flog2Space;
export default flog2;
