// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface GraySpace extends ColorSpace {
	name: 'gray';
	range: [[0, 1]];
}

declare const gray: GraySpace;
export default gray;
