// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface HcgSpace extends ColorSpace {
	name: 'hcg';
}

declare const hcg: HcgSpace;
export default hcg;
