// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface HclSpace extends ColorSpace {
	name: 'hcl';
	range: [[0, 360], [0, 100], [0, 95]];
}

declare const hcl: HclSpace;
export default hcl;
