// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface HctSpace extends ColorSpace {
	name: 'hct';
	range: [[0, 360], [0, 145], [0, 100]];
}

declare const hct: HctSpace;
export default hct;
