// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface HcySpace extends ColorSpace {
	name: 'hcy';
	range: [[0, 360], [0, 100], [0, 100]];
}

declare const hcy: HcySpace;
export default hcy;
