// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface Hdr_iptSpace extends ColorSpace {
	name: 'hdr-ipt';
	range: [[0, 100], [-100, 100], [-100, 100]];
}

declare const hdr_ipt: Hdr_iptSpace;
export default hdr_ipt;
