// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface Hdr_cie_labSpace extends ColorSpace {
	name: 'hdr-cie-lab';
	range: [[0, 100], [-100, 100], [-100, 100]];
}

declare const hdr_cie_lab: Hdr_cie_labSpace;
export default hdr_cie_lab;
