// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface Hellwig2022Space extends ColorSpace {
	name: 'hellwig2022';
	range: [[0, 100], [0, 60], [0, 360]];
}

declare const hellwig2022: Hellwig2022Space;
export default hellwig2022;
