// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface HpluvSpace extends ColorSpace {
	name: 'hpluv';
	range: [[0, 360], [0, 100], [0, 100]];
}

declare const hpluv: HpluvSpace;
export default hpluv;
