// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface HsiSpace extends ColorSpace {
	name: 'hsi';
}

declare const hsi: HsiSpace;
export default hsi;
