// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface HslSpace extends ColorSpace {
	name: 'hsl';
}

declare const hsl: HslSpace;
export default hsl;
