// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface HslSpace extends ColorSpace {
	name: 'hsl';
	range: [[0, 360], [0, 100], [0, 100]];
}

declare const hsl: HslSpace;
export default hsl;
