// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface HsluvSpace extends ColorSpace {
	name: 'hsluv';
	range: [[0, 360], [0, 100], [0, 100]];
}

declare const hsluv: HsluvSpace;
export default hsluv;
