// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface HsmSpace extends ColorSpace {
	name: 'hsm';
	range: [[0, 360], [0, 100], [0, 100]];
}

declare const hsm: HsmSpace;
export default hsm;
