// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface HspSpace extends ColorSpace {
	name: 'hsp';
	range: [[0, 360], [0, 100], [0, 100]];
}

declare const hsp: HspSpace;
export default hsp;
