// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface HuntSpace extends ColorSpace {
	name: 'hunt';
	range: [[0, 100], [0, 120], [0, 360]];
}

declare const hunt: HuntSpace;
export default hunt;
