// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface HwbSpace extends ColorSpace {
	name: 'hwb';
}

declare const hwb: HwbSpace;
export default hwb;
