// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface IcacbSpace extends ColorSpace {
	name: 'icacb';
	range: [[0, 1], [-0.5, 0.5], [-0.5, 0.5]];
}

declare const icacb: IcacbSpace;
export default icacb;
