// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface IctcpSpace extends ColorSpace {
	name: 'ictcp';
	range: [[0, 1], [-0.5, 0.5], [-0.5, 0.5]];
}

declare const ictcp: IctcpSpace;
export default ictcp;
