// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface IctcpSpace extends ColorSpace {
	name: 'ictcp';
}

declare const ictcp: IctcpSpace;
export default ictcp;
