// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface IgpgtgSpace extends ColorSpace {
	name: 'igpgtg';
	range: [[0, 1], [-1, 1], [-1, 1]];
}

declare const igpgtg: IgpgtgSpace;
export default igpgtg;
