// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface IptSpace extends ColorSpace {
	name: 'ipt';
	range: [[0, 1], [-1, 1], [-1, 1]];
}

declare const ipt: IptSpace;
export default ipt;
