// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface IzazbzSpace extends ColorSpace {
	name: 'izazbz';
	range: [[0, 1], [-0.5, 0.5], [-0.5, 0.5]];
}

declare const izazbz: IzazbzSpace;
export default izazbz;
