// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface JpegSpace extends ColorSpace {
	name: 'jpeg';
	range: [[0, 255], [0, 255], [0, 255]];
}

declare const jpeg: JpegSpace;
export default jpeg;
