// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface JzazbzSpace extends ColorSpace {
	name: 'jzazbz';
}

declare const jzazbz: JzazbzSpace;
export default jzazbz;
