// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface JzczhzSpace extends ColorSpace {
	name: 'jzczhz';
}

declare const jzczhz: JzczhzSpace;
export default jzczhz;
