// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface JzczhzSpace extends ColorSpace {
	name: 'jzczhz';
	range: [[0, 1], [0, 1], [0, 360]];
}

declare const jzczhz: JzczhzSpace;
export default jzczhz;
