// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface KelvinSpace extends ColorSpace {
	name: 'kelvin';
	range: [[1000, 25000]];
}

declare const kelvin: KelvinSpace;
export default kelvin;
