// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface Lab_d65Space extends ColorSpace {
	name: 'lab-d65';
	range: [[0, 100], [-125, 125], [-125, 125]];
}

declare const lab_d65: Lab_d65Space;
export default lab_d65;
