// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface LabSpace extends ColorSpace {
	name: 'lab';
	range: [[0, 100], [-125, 125], [-125, 125]];
}

declare const lab: LabSpace;
export default lab;
