// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface LabhSpace extends ColorSpace {
	name: 'labh';
	range: [[0, 100], [-75, 115], [-210, 60]];
}

declare const labh: LabhSpace;
export default labh;
