// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface LalphabetaSpace extends ColorSpace {
	name: 'lalphabeta';
	range: [[-10.4, 0], [-3, 3], [-3, 3]];
}

declare const lalphabeta: LalphabetaSpace;
export default lalphabeta;
