// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface LalphabetaSpace extends ColorSpace {
	name: 'lalphabeta';
	range: [[-6, 0], [-1, 0.9], [-0.21, 0.21]];
}

declare const lalphabeta: LalphabetaSpace;
export default lalphabeta;
