// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface Lch_d65Space extends ColorSpace {
	name: 'lch-d65';
	range: [[0, 100], [0, 150], [0, 360]];
}

declare const lch_d65: Lch_d65Space;
export default lch_d65;
