// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface LchabSpace extends ColorSpace {
	name: 'lchab';
}

declare const lchab: LchabSpace;
export default lchab;
