// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface LchabSpace extends ColorSpace {
	name: 'lchab';
	range: [[0, 100], [0, 150], [0, 360]];
}

declare const lchab: LchabSpace;
export default lchab;
