// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface LchuvSpace extends ColorSpace {
	name: 'lchuv';
}

declare const lchuv: LchuvSpace;
export default lchuv;
