// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface LchuvSpace extends ColorSpace {
	name: 'lchuv';
	range: [[0, 100], [0, 220], [0, 360]];
}

declare const lchuv: LchuvSpace;
export default lchuv;
