// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace, Convert } from './color-space';
import clog2 from './clog2';
import din99d from './din99d';
import din99o_lab from './din99o-lab';
import din99o_lch from './din99o-lch';
import hpluv from './hpluv';
import hsluv from './hsluv';
import ictcp from './ictcp';
import ipt from './ipt';
import jzazbz from './jzazbz';
import jzczhz from './jzczhz';
import lab from './lab';
import lab_d65 from './lab-d65';
import lch_d65 from './lch-d65';
import lchab from './lchab';
import lchuv from './lchuv';
import log3g10 from './log3g10';
import logc4 from './logc4';
import lrgb from './lrgb';
import luv from './luv';
import oklab from './oklab';
import oklch from './oklch';
import oklrab from './oklrab';
import oklrch from './oklrch';
import rgb from './rgb';
import slog3 from './slog3';
import vlog from './vlog';
import xyz from './xyz';

export { ColorSpace, Convert };
export { clog2, din99d, din99o_lab, din99o_lch, hpluv, hsluv, ictcp, ipt, jzazbz, jzczhz, lab, lab_d65, lch_d65, lchab, lchuv, log3g10, logc4, lrgb, luv, oklab, oklch, oklrab, oklrch, rgb, slog3, vlog, xyz };

/** The compact space set (mirrors color-space/wasm coverage), keyed by name. */
declare const space: { [name: string]: ColorSpace };
export default space;

/** Register a custom space and wire conversions to/from every existing space. */
export function register(newSpace: ColorSpace): { [name: string]: ColorSpace };
