// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface LlabSpace extends ColorSpace {
	name: 'llab';
	range: [[-10, 100], [-80, 100], [-90, 90]];
}

declare const llab: LlabSpace;
export default llab;
