// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface LlogSpace extends ColorSpace {
	name: 'llog';
	range: [[0, 1], [0, 1], [0, 1]];
}

declare const llog: LlogSpace;
export default llog;
