// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface LmsSpace extends ColorSpace {
	name: 'lms';
	range: [[0, 100], [0, 105], [0, 110]];
}

declare const lms: LmsSpace;
export default lms;
