// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface LmsSpace extends ColorSpace {
	name: 'lms';
}

declare const lms: LmsSpace;
export default lms;
