// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface Log3g10Space extends ColorSpace {
	name: 'log3g10';
	range: [[0, 1], [0, 1], [0, 1]];
}

declare const log3g10: Log3g10Space;
export default log3g10;
