// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface Log3g12Space extends ColorSpace {
	name: 'log3g12';
	range: [[0, 1], [0, 1], [0, 1]];
}

declare const log3g12: Log3g12Space;
export default log3g12;
