// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface Logc3Space extends ColorSpace {
	name: 'logc3';
	range: [[0, 1], [0, 1], [0, 1]];
}

declare const logc3: Logc3Space;
export default logc3;
