// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface Logc4Space extends ColorSpace {
	name: 'logc4';
	range: [[0, 1], [0, 1], [0, 1]];
}

declare const logc4: Logc4Space;
export default logc4;
