// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface LrgbSpace extends ColorSpace {
	name: 'lrgb';
}

declare const lrgb: LrgbSpace;
export default lrgb;
