// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

/** A sampled conversion lattice: 0–1-normalized output triples (3D is red-fastest). */
export interface LutTable {
	from: ColorSpace;
	to: ColorSpace;
	dims: 1 | 3;
	size: number;
	domain: ReadonlyArray<readonly [number, number]>;
	range: ReadonlyArray<readonly [number, number]>;
	data: Float64Array;
}

/** Off-lattice deviation vs the direct conversion, as fractions of the target's full scale. */
export interface LutStats {
	max: number;
	median: number;
	n: number;
	/** over samples whose direct result lands inside the target range — the LUT's working set; n is the count actually collected */
	in: { max: number; median: number; share: number; n: number };
}

/** Is the conversion purely per-channel (a transfer curve, no cross-channel term)? */
export function channelwise(from: ColorSpace, to: ColorSpace): boolean;

/** Sample a conversion into a LUT lattice. */
export function table(from: ColorSpace, to: ColorSpace, opts?: { size?: number; dims?: 1 | 3 }): LutTable;

/** Read one color through the lattice (linear/trilinear), native units on both ends. */
export function apply(tab: LutTable, vals: number[]): number[];

/** Measure the lattice against the direct conversion at random off-lattice points. */
export function verify(tab: LutTable, n?: number): LutStats;

/** Render a conversion as a .cube file (Resolve, Premiere, Final Cut, OBS, ffmpeg). */
export function cube(from: ColorSpace, to: ColorSpace, opts?: { size?: number; dims?: 1 | 3; title?: string; verify?: number | false }): string;
