// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface LuvSpace extends ColorSpace {
	name: 'luv';
	range: [[0, 100], [-100, 100], [-100, 100]];
}

declare const luv: LuvSpace;
export default luv;
