// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface LuvSpace extends ColorSpace {
	name: 'luv';
}

declare const luv: LuvSpace;
export default luv;
