// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface MacboynSpace extends ColorSpace {
	name: 'macboyn';
	range: [[0, 1], [0, 1], [0, 100]];
}

declare const macboyn: MacboynSpace;
export default macboyn;
