// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface MunsellSpace extends ColorSpace {
	name: 'munsell';
	range: [[0, 100], [0, 10], [0, 38]];
}

declare const munsell: MunsellSpace;
export default munsell;
