// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface Nayatani95Space extends ColorSpace {
	name: 'nayatani95';
	range: [[-20, 115], [0, 190], [0, 360]];
}

declare const nayatani95: Nayatani95Space;
export default nayatani95;
