// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface NlogSpace extends ColorSpace {
	name: 'nlog';
	range: [[0, 1], [0, 1], [0, 1]];
}

declare const nlog: NlogSpace;
export default nlog;
