// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface NtscSpace extends ColorSpace {
	name: 'ntsc';
	range: [[0, 1], [0, 1], [0, 1]];
}

declare const ntsc: NtscSpace;
export default ntsc;
