// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface OhtaSpace extends ColorSpace {
	name: 'ohta';
}

declare const ohta: OhtaSpace;
export default ohta;
