// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface OhtaSpace extends ColorSpace {
	name: 'ohta';
	range: [[0, 255], [-128, 128], [-128, 128]];
}

declare const ohta: OhtaSpace;
export default ohta;
