// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface OkhsvSpace extends ColorSpace {
	name: 'okhsv';
	range: [[0, 360], [0, 100], [0, 100]];
}

declare const okhsv: OkhsvSpace;
export default okhsv;
