// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface OkhslSpace extends ColorSpace {
	name: 'okhsl';
	range: [[0, 360], [0, 100], [0, 100]];
}

declare const okhsl: OkhslSpace;
export default okhsl;
