// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface OklabSpace extends ColorSpace {
	name: 'oklab';
}

declare const oklab: OklabSpace;
export default oklab;
