// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface OklchSpace extends ColorSpace {
	name: 'oklch';
}

declare const oklch: OklchSpace;
export default oklch;
