// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface OklchSpace extends ColorSpace {
	name: 'oklch';
	range: [[0, 1], [0, 0.4], [0, 360]];
}

declare const oklch: OklchSpace;
export default oklch;
