// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface OklrchSpace extends ColorSpace {
	name: 'oklrch';
}

declare const oklrch: OklrchSpace;
export default oklrch;
