// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface OklrabSpace extends ColorSpace {
	name: 'oklrab';
}

declare const oklrab: OklrabSpace;
export default oklrab;
