// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface OlogSpace extends ColorSpace {
	name: 'olog';
	range: [[0, 1], [0, 1], [0, 1]];
}

declare const olog: OlogSpace;
export default olog;
