// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface OsaucsSpace extends ColorSpace {
	name: 'osaucs';
	range: [[-10, 10], [-10, 10], [-10, 10]];
}

declare const osaucs: OsaucsSpace;
export default osaucs;
