// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface OstwaldSpace extends ColorSpace {
	name: 'ostwald';
	range: [[0, 360], [0, 100], [0, 100]];
}

declare const ostwald: OstwaldSpace;
export default ostwald;
