// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface P3_linearSpace extends ColorSpace {
	name: 'p3-linear';
}

declare const p3_linear: P3_linearSpace;
export default p3_linear;
