// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface P3Space extends ColorSpace {
	name: 'p3';
}

declare const p3: P3Space;
export default p3;
