// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface PalSpace extends ColorSpace {
	name: 'pal';
	range: [[0, 1], [0, 1], [0, 1]];
}

declare const pal: PalSpace;
export default pal;
