// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface PanalogSpace extends ColorSpace {
	name: 'panalog';
	range: [[0, 1], [0, 1], [0, 1]];
}

declare const panalog: PanalogSpace;
export default panalog;
