// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface PhotoyccSpace extends ColorSpace {
	name: 'photoycc';
}

declare const photoycc: PhotoyccSpace;
export default photoycc;
