// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface ProlabSpace extends ColorSpace {
	name: 'prolab';
	range: [[0, 100], [-125, 125], [-125, 125]];
}

declare const prolab: ProlabSpace;
export default prolab;
