// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface ProphotoSpace extends ColorSpace {
	name: 'prophoto';
}

declare const prophoto: ProphotoSpace;
export default prophoto;
