// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface ProphotoSpace extends ColorSpace {
	name: 'prophoto';
	range: [[0, 1], [0, 1], [0, 1]];
}

declare const prophoto: ProphotoSpace;
export default prophoto;
