// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface ProtuneSpace extends ColorSpace {
	name: 'protune';
	range: [[0, 1], [0, 1], [0, 1]];
}

declare const protune: ProtuneSpace;
export default protune;
