// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface Ral_designSpace extends ColorSpace {
	name: 'ral-design';
}

declare const ral_design: Ral_designSpace;
export default ral_design;
