// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface Rec2100_linearSpace extends ColorSpace {
	name: 'rec2100-linear';
}

declare const rec2100_linear: Rec2100_linearSpace;
export default rec2100_linear;
