// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface Rec2020_oetfSpace extends ColorSpace {
	name: 'rec2020-oetf';
}

declare const rec2020_oetf: Rec2020_oetfSpace;
export default rec2020_oetf;
