// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface Rec2100_hlgSpace extends ColorSpace {
	name: 'rec2100-hlg';
}

declare const rec2100_hlg: Rec2100_hlgSpace;
export default rec2100_hlg;
