// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface Rec2020Space extends ColorSpace {
	name: 'rec2020';
}

declare const rec2020: Rec2020Space;
export default rec2020;
