// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface Rec2020_linearSpace extends ColorSpace {
	name: 'rec2020-linear';
}

declare const rec2020_linear: Rec2020_linearSpace;
export default rec2020_linear;
