// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface Rec709Space extends ColorSpace {
	name: 'rec709';
	range: [[0, 1], [0, 1], [0, 1]];
}

declare const rec709: Rec709Space;
export default rec709;
