// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface RedlogSpace extends ColorSpace {
	name: 'redlog';
	range: [[0, 1], [0, 1], [0, 1]];
}

declare const redlog: RedlogSpace;
export default redlog;
