// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface RedlogfilmSpace extends ColorSpace {
	name: 'redlogfilm';
	range: [[0, 1], [0, 1], [0, 1]];
}

declare const redlogfilm: RedlogfilmSpace;
export default redlogfilm;
