// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface RgSpace extends ColorSpace {
	name: 'rg';
}

declare const rg: RgSpace;
export default rg;
