// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface RgbSpace extends ColorSpace {
	name: 'rgb';
	range: [[0, 255], [0, 255], [0, 255]];
}

declare const rgb: RgbSpace;
export default rgb;
