// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface RimmSpace extends ColorSpace {
	name: 'rimm';
	range: [[0, 1], [0, 1], [0, 1]];
}

declare const rimm: RimmSpace;
export default rimm;
