// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface RybSpace extends ColorSpace {
	name: 'ryb';
	range: [[0, 255], [0, 255], [0, 255]];
}

declare const ryb: RybSpace;
export default ryb;
