// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface ScrgbSpace extends ColorSpace {
	name: 'scrgb';
	range: [[-0.5, 7.4998779296875], [-0.5, 7.4998779296875], [-0.5, 7.4998779296875]];
}

declare const scrgb: ScrgbSpace;
export default scrgb;
