// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface Slog2Space extends ColorSpace {
	name: 'slog2';
	range: [[0, 1], [0, 1], [0, 1]];
}

declare const slog2: Slog2Space;
export default slog2;
