// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface SlogSpace extends ColorSpace {
	name: 'slog';
	range: [[0, 1], [0, 1], [0, 1]];
}

declare const slog: SlogSpace;
export default slog;
