// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface Slog3Space extends ColorSpace {
	name: 'slog3';
	range: [[0, 1], [0, 1], [0, 1]];
}

declare const slog3: Slog3Space;
export default slog3;
