// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface Smpte_240mSpace extends ColorSpace {
	name: 'smpte-240m';
	range: [[0, 1], [0, 1], [0, 1]];
}

declare const smpte_240m: Smpte_240mSpace;
export default smpte_240m;
