// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface Smpte_cSpace extends ColorSpace {
	name: 'smpte-c';
	range: [[0, 1], [0, 1], [0, 1]];
}

declare const smpte_c: Smpte_cSpace;
export default smpte_c;
