// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface Srlab2Space extends ColorSpace {
	name: 'srlab2';
	range: [[0, 100], [-125, 125], [-125, 125]];
}

declare const srlab2: Srlab2Space;
export default srlab2;
