// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface SucsSpace extends ColorSpace {
	name: 'sucs';
	range: [[0, 100], [-50, 50], [-50, 50]];
}

declare const sucs: SucsSpace;
export default sucs;
