// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface TslSpace extends ColorSpace {
	name: 'tsl';
}

declare const tsl: TslSpace;
export default tsl;
