// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface TslSpace extends ColorSpace {
	name: 'tsl';
	range: [[0, 360], [0, 1], [0, 255]];
}

declare const tsl: TslSpace;
export default tsl;
