// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface UcsSpace extends ColorSpace {
	name: 'ucs';
}

declare const ucs: UcsSpace;
export default ucs;
