// Generated by scripts/generate-types.js — do not edit by hand
/** 3×3 matrix (row-major, 9 elements) times a 3-vector. */
export declare const mat3: (m: number[], x: number, y: number, z: number) => [number, number, number];
