// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface UvSpace extends ColorSpace {
	name: 'uv';
}

declare const uv: UvSpace;
export default uv;
