// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface UvwSpace extends ColorSpace {
	name: 'uvw';
}

declare const uvw: UvwSpace;
export default uvw;
