// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface ViperlogSpace extends ColorSpace {
	name: 'viperlog';
	range: [[0, 1], [0, 1], [0, 1]];
}

declare const viperlog: ViperlogSpace;
export default viperlog;
