// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface VlogSpace extends ColorSpace {
	name: 'vlog';
	range: [[0, 1], [0, 1], [0, 1]];
}

declare const vlog: VlogSpace;
export default vlog;
