// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface WavelengthSpace extends ColorSpace {
	name: 'wavelength';
	range: [[380, 700]];
}

declare const wavelength: WavelengthSpace;
export default wavelength;
