// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface XvyccSpace extends ColorSpace {
	name: 'xvycc';
	range: [[16, 235], [16, 240], [16, 240]];
}

declare const xvycc: XvyccSpace;
export default xvycc;
