// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface XvyccSpace extends ColorSpace {
	name: 'xvycc';
	range: [[0, 255], [0, 255], [0, 255]];
}

declare const xvycc: XvyccSpace;
export default xvycc;
