// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface XybSpace extends ColorSpace {
	name: 'xyb';
	range: [[-0.0154, 0.0281], [0, 0.8453], [-0.2778, 0.388]];
}

declare const xyb: XybSpace;
export default xyb;
