// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface XyySpace extends ColorSpace {
	name: 'xyy';
}

declare const xyy: XyySpace;
export default xyy;
