// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface Xyz_abs_d65Space extends ColorSpace {
	name: 'xyz-abs-d65';
	range: [[0, 10000], [0, 10000], [0, 10000]];
}

declare const xyz_abs_d65: Xyz_abs_d65Space;
export default xyz_abs_d65;
