// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface Xyz_d50Space extends ColorSpace {
	name: 'xyz-d50';
	range: [[0, 100], [0, 100], [0, 100]];
}

declare const xyz_d50: Xyz_d50Space;
export default xyz_d50;
