// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface XyzSpace extends ColorSpace {
	name: 'xyz';
}

declare const xyz: XyzSpace;
export default xyz;
