// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface YcbcrSpace extends ColorSpace {
	name: 'ycbcr';
}

declare const ycbcr: YcbcrSpace;
export default ycbcr;
