// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface YccbccrcSpace extends ColorSpace {
	name: 'yccbccrc';
	range: [[0, 1], [-0.5, 0.5], [-0.5, 0.5]];
}

declare const yccbccrc: YccbccrcSpace;
export default yccbccrc;
