// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface YdbdrSpace extends ColorSpace {
	name: 'ydbdr';
	range: [[0, 1], [-1.333, 1.333], [-1.333, 1.333]];
}

declare const ydbdr: YdbdrSpace;
export default ydbdr;
