// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface YesSpace extends ColorSpace {
	name: 'yes';
	range: [[0, 1], [-0.5, 0.5], [-0.5, 0.5]];
}

declare const yes: YesSpace;
export default yes;
