// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface YiqSpace extends ColorSpace {
	name: 'yiq';
}

declare const yiq: YiqSpace;
export default yiq;
