// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface YpbprSpace extends ColorSpace {
	name: 'ypbpr';
}

declare const ypbpr: YpbprSpace;
export default ypbpr;
