// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface YpbprSpace extends ColorSpace {
	name: 'ypbpr';
	range: [[0, 1], [-0.5, 0.5], [-0.5, 0.5]];
}

declare const ypbpr: YpbprSpace;
export default ypbpr;
