// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface YrgSpace extends ColorSpace {
	name: 'yrg';
	range: [[0, 1], [0, 1], [0, 1]];
}

declare const yrg: YrgSpace;
export default yrg;
