// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface YuvSpace extends ColorSpace {
	name: 'yuv';
}

declare const yuv: YuvSpace;
export default yuv;
