// Generated by scripts/generate-types.js — do not edit by hand
import { ColorSpace } from './color-space';

export interface ZcamSpace extends ColorSpace {
	name: 'zcam';
	range: [[0, 100], [0, 100], [0, 360]];
}

declare const zcam: ZcamSpace;
export default zcam;
