// Catalog sections (README grouping). Spaces not listed fall into "more".
// Order within a section = popularity/relevance: the first three are its folded preview.
// tip: the family in two sentences — what unites it and who defines it (TOC + heading tooltip).
export default [
	{ name: 'Display & web', tip: 'RGB working and delivery spaces – primaries, a white point and a transfer curve on one cube. Defined by standards bodies and display vendors: IEC, ITU-R, SMPTE, Adobe, Apple.', spaces: ['rgb', 'p3', 'rec2020', 'lrgb', 'rec709', 'prophoto', 'a98rgb', 'dci-p3', 'p3-linear', 'rec2020-linear', 'a98rgb-linear', 'prophoto-linear', 'scrgb', 'rimm', 'cie-rgb', 'ntsc', 'pal', 'apple-rgb', 'smpte-240m'] },
	{ name: 'Cylindrical', tip: 'Hue-led remixes of RGB born in 1970s computer graphics – cheap picker math with no perceptual claims: equal numeric steps do not look equal.', spaces: ['hsl', 'hsv', 'hwb', 'hsi', 'hcg', 'hcl', 'hsp', 'hcy', 'hsm'] },
	{ name: 'Perceptual – modern', tip: 'Spaces rebuilt so equal steps look equal, fitted to modern perception datasets – mostly individual researchers and design-system teams correcting CIELAB’s unevenness.', spaces: ['oklch', 'oklab', 'hct', 'okhsl', 'okhsv', 'okhwb', 'oklrab', 'oklrch', 'srlab2', 'prolab', 'sucs', 'igpgtg'] },
	{ name: 'Perceptual – CIE classic', tip: 'The CIE’s 1976 uniform spaces and their industrial refinements – the shared language of color difference ever since (ISO/CIE 11664, DIN 6176).', spaces: ['lab', 'lchab', 'luv', 'hsluv', 'lchuv', 'lab-d65', 'lch-d65', 'hpluv', 'din99o-lab', 'din99o-lch', 'din99d', 'labh', 'ucs', 'uvw', 'anlab'] },
	{ name: 'HDR & wide gamut', tip: 'Encodings for brighter-than-white and wider-than-sRGB signals – ITU-R BT.2100 broadcast standards, Dolby research, and HDR-tuned successors of Lab.', spaces: ['ictcp', 'jzazbz', 'rec2100-pq', 'rec2100-hlg', 'jzczhz', 'ipt', 'izazbz', 'rec2100-linear', 'hdr-ipt', 'hdr-cie-lab', 'icacb'] },
	{ name: 'Colorimetry & vision', tip: 'The measurement layer every other family is defined through – the CIE’s standard-observer spaces and the physiological coordinates of the eye.', spaces: ['xyz', 'xyy', 'lms', 'xyz-d50', 'uv', 'cct-duv', 'kelvin', 'maxwell', 'wavelength', 'xyz-abs-d65', 'macboyn', 'dkl', 'gray', 'dsh', 'rg', 'yrg'] },
	{ name: 'Video & broadcast', tip: 'Luma-plus-chroma encodings built to save bandwidth, not to look uniform – ITU-R and SMPTE broadcast standards from analog NTSC to digital UHDTV.', spaces: ['ycbcr-bt709', 'ycbcr-bt2020', 'ycbcr-bt601-525', 'ycbcr-bt601-625', 'ycbcr', 'yuv', 'yiq', 'ypbpr', 'ycgco', 'jpeg', 'ydbdr', 'yccbccrc', 'xvycc', 'smpte-c', 'photoycc'] },
	{ name: 'Film & camera', tip: 'Each vendor’s log curve and wide gamut packing sensor dynamic range into recordable code values – ARRI, Sony, RED, Canon, Panasonic – plus the Academy’s interchange standards (SMPTE ST 2065).', spaces: ['acescg', 'acescc', 'logc3', 'slog3', 'sgamut3cine', 'aces2065-1', 'acescct', 'logc4', 'cineon', 'davinci', 'slog2', 'vlog', 'log3g10', 'clog', 'clog2', 'clog3', 'flog', 'flog2', 'nlog', 'applelog', 'bmdfilm', 'dlog', 'tlog', 'dcdm', 'slog', 'acesproxy', 'erimm', 'llog', 'protune', 'milog', 'olog', 'redlog', 'redlogfilm', 'log3g12', 'panalog', 'viperlog', 'filmicpro'] },
	{ name: 'Appearance models', tip: 'CIE-track science predicting how a color appears in context – adaptation, background, viewing conditions. Heavier math, for research and cross-media matching.', spaces: ['cam16', 'ciecam02', 'cam16-ucs', 'zcam', 'cam02-ucs', 'cam16-lcd', 'cam16-scd', 'cam02-lcd', 'cam02-scd', 'hellwig2022', 'rlab', 'llab', 'nayatani95', 'hunt', 'atd95'] },
	{ name: 'Print & physical', tip: 'Ink, paint and surface-color systems – subtractive process models and the color-order atlases of national and industrial standards.', spaces: ['cmyk', 'munsell', 'ryb', 'cmy', 'ral-design', 'coloroid', 'ostwald'] },
	{ name: 'Specialty & research', tip: 'Single-purpose coordinates from imaging research – codec internals, machine-vision segmentation, statistical color transfer – and the Optical Society’s uniform lattice.', spaces: ['xyb', 'osaucs', 'tsl', 'yes', 'ohta', 'lalphabeta'] },
]
