// The dossier's curated layer — judgment and etymology that library metadata
// doesn't carry (meta.js owns year/by/use; this file never duplicates those).
//   for: the problem the space was born to solve
//   sin: the known failure mode, in one honest line
//   nm: how to read the name
// A field appears only where the fact is solid (each space's primary source is in
// meta.refs); absence means "not confidently known", never "nothing to say".
export default {
	// ── display & web ──
	rgb: { for: 'one default color for monitors, printers and the web — the average 1990s CRT, standardized', sin: 'gamma-encoded: averaging two colors numerically gives a darker color than mixing their light', nm: 'the s in sRGB is “standard”' },
	lrgb: { for: 'the linear-light form — where physical math (blending, shading, resampling) is correct', sin: 'perceptually lopsided: three quarters of its numeric range covers the brightest stops' },
	p3: { for: 'DCI cinema primaries domesticated for displays — D65 white, sRGB curve', nm: 'Display P3 — the P3 gamut minus the projector' },
	'dci-p3': { for: 'a gamut real xenon projectors could cover', sin: 'its native white is greenish ~6300 K cinema white, not D65 — grading for TV needs adaptation' },
	rec2020: { for: 'the UHD container gamut', sin: 'primaries are pure laser wavelengths — no consumer display fully covers it, so most Rec.2020 content is smaller than its box' },
	'rec2020-linear': { for: 'Rec.2020 in linear light, for compositing math' },
	rec709: { for: 'the HDTV standard — sRGB later borrowed its primaries', nm: 'named for ITU-R Recommendation BT.709' },
	prophoto: { for: 'room for everything film and future printers could hold', sin: 'two primaries are imaginary — ~13% of its volume is no color at all, and 8-bit files band visibly', nm: 'standardized as ROMM RGB (Reference Output Medium Metric)' },
	'prophoto-linear': { for: 'ProPhoto in linear light' },
	a98rgb: { for: 'a Photoshop working space reaching printable cyans and greens', sin: 'born of a bug — an engineer transcribed SMPTE 240M primaries wrong, and the accident shipped', nm: 'the “98” is the year' },
	'a98rgb-linear': { for: 'Adobe RGB in linear light' },
	'p3-linear': { for: 'Display P3 in linear light' },
	scrgb: { for: 'sRGB with headroom — negatives and >1 allowed for HDR compositing on Windows', sin: 'most software clips its out-of-range values on sight', nm: 'sc = “scene” sRGB' },
	rimm: { for: 'the scene-referred sibling of ROMM — camera light before rendering', nm: 'Reference Input Medium Metric' },
	'cie-rgb': { for: 'the primaries of the Wright–Guild experiments that defined the standard observer', sin: 'needs negative red to match spectral cyans — the very problem XYZ was invented to hide' },
	ntsc: { for: 'the first broadcast color gamut', sin: 'no consumer set ever matched its phosphors — it survives mainly as a marketing benchmark (“72% NTSC”)' },
	pal: { for: 'European broadcast phosphors (EBU Tech 3213)' },
	'apple-rgb': { for: 'the classic Mac Trinitron display, frozen as a profile' },
	'smpte-240m': { for: 'interim HDTV before Rec.709 settled', sin: 'remembered mostly because misreading its numbers created Adobe RGB' },

	// ── cylindrical ──
	hsl: { for: 'hue controls cheap enough for 1970s framebuffers', sin: 'L=50 is not one brightness: yellow at L=50 emits ~4× the luminance of blue', nm: 'lightness — the double-cone: L=100 is always white' },
	hsv: { for: 'painter-style “tints and shades” for early paint programs', sin: 'V is just max(R,G,B): full-value blue and yellow claim equal brightness and are nowhere near', nm: 'aka HSB; V=100 is the pure hue, not white' },
	hwb: { for: 'mixing the way painters think — a hue plus white plus black', sin: 'W+B>100 all collapse to the same gray: a whole wedge of coordinates means nothing', nm: 'hue · whiteness · blackness, now native in CSS' },
	hsi: { for: 'machine-vision variant where I is the plain mean of R,G,B', sin: 'hue is numerically unstable near gray — sensor noise sends it spinning' },
	hcg: { for: 'HSV refactored as chroma plus gray base' },
	hcl: { for: 'hue–chroma–luminance picker math (not the Lab-based LCh)' },
	hsp: { for: 'HSV with a brightness that matches the eye', nm: 'P = perceived brightness, a weighted RMS of R,G,B' },
	hcy: { for: 'shader-friendly hue–chroma over Rec.601 luma' },
	hsm: { for: 'hue–saturation–mixture, built for skin segmentation research' },

	// ── perceptual, modern ──
	oklab: { for: 'Lab’s job without Lab’s blue drift — fitted to CAM16 data, cheap enough for a shader', sin: 'tuned for D65 display work — it has no viewing-conditions story at all, by design', nm: '“OK” is literal: named for doing an OK job' },
	oklch: { for: 'the polar form CSS adopted — perceptual hue and chroma as dials', nm: 'lightness, chroma, hue — OKLab in polar form' },
	okhsl: { for: 'an HSL whose saturation and lightness keep their promises, mapped to the sRGB gamut', sin: 'sRGB-bound by construction — there is no wide-gamut okhsl' },
	okhsv: { for: 'the HSV counterpart — perceptual tints and shades inside sRGB', sin: 'sRGB-bound by construction' },
	okhwb: { for: 'HWB’s white/black mixing lifted onto the okhsv machinery' },
	oklrab: { for: 'OKLab with Lr — lightness given a toe so mid-grays sit where displays put them', nm: 'Lr = lightness, reference-white version' },
	oklrch: { for: 'the polar form of OKLrab', nm: 'Lr (toe-corrected lightness), chroma, hue — OKLrab in polar form' },
	hct: { for: 'dynamic theming: pick tone for contrast, keep hue and chroma honest', sin: 'two models stitched together — CAM16 hue/chroma with Lab tone — so the inverse needs a solver', nm: 'hue · chroma · tone' },
	srlab2: { for: 'CIELAB’s structure with OSA-grade hue uniformity, kept invertible' },
	prolab: { for: 'a projective transform of XYZ that stays perceptually even — angles survive illumination change' },
	sucs: { for: 'a lightweight uniform chromaticity model for embedded use' },
	igpgtg: { for: 'an IPT-style space refit on newer cone fundamentals' },

	// ── perceptual, CIE classic ──
	lab: { for: 'make color difference measurable — one number, ΔE, for “how far apart”', sin: 'constant-hue lines bend in blue: Lab gradients drift toward purple', nm: 'the * in L*a*b* set it apart from Hunter’s 1948 Lab' },
	lchab: { for: 'Lab in polar form — chroma and hue as dials', nm: 'LCh(ab): C=√(a²+b²), h=atan2(b,a)' },
	'lab-d65': { for: 'Lab referenced to D65 — display work without the D50 detour' },
	'lch-d65': { for: 'the polar form of Lab-D65' },
	luv: { for: 'the additive-light sibling of Lab — chromaticity stays projective, so light mixtures travel in straight lines', sin: 'good for lights, worse for surfaces — print went Lab, lighting went Luv', nm: 'u,v come from the 1960 uniform chromaticity diagram' },
	lchuv: { for: 'polar Luv' },
	hsluv: { for: 'an HSL that never lies about lightness — L is CIE L*, saturation is share of the possible chroma', nm: 'born “HUSL”, renamed HSLuv' },
	hpluv: { for: 'the pastel variant — chroma capped so every hue can reach it', sin: 'only pastels: the cap is the dullest hue’s maximum' },
	'din99o-lab': { for: 'warp Lab so plain Euclidean distance works as ΔE', nm: '“99” is the year, “o” the optimized revision' },
	'din99o-lch': { for: 'polar DIN99o' },
	din99d: { for: 'the DIN99 revision tuned for small differences' },
	labh: { for: 'uniform-ish readings straight from photoelectric colorimeters — square roots, no cube roots', sin: 'superseded by CIELAB everywhere except legacy instrument firmware', nm: 'the starless Lab — CIE added the * in 1976 to avoid the collision' },
	ucs: { for: 'a chromaticity diagram where distance means something', sin: 'obsolete — it survives only inside correlated color temperature math', nm: 'Uniform Chromaticity Scale' },
	uvw: { for: 'the first CIE uniform 3-D space, built for color rendering index', sin: 'obsolete — CRI is the only place you will meet it' },
	anlab: { for: 'chromatic-valence ΔE for textiles — the direct ancestor of CIELAB' },

	// ── HDR & wide gamut ──
	ictcp: { for: 'HDR grading axes that keep luminance out of chroma, PQ-encoded', nm: 'I intensity · Ct tritan (blue–yellow) · Cp protan (red–green)' },
	jzazbz: { for: 'a Lab that stays uniform to 10,000 nits', sin: 'built on PQ: values depend on absolute luminance, so SDR use needs a brightness assumption', nm: 'Lab’s letters in PQ dress — Jz, az, bz' },
	jzczhz: { for: 'polar Jzazbz' },
	'rec2100-pq': { for: 'absolute HDR signals — code steps sized to the eye’s contrast threshold', nm: 'PQ = perceptual quantizer (SMPTE ST 2084)' },
	'rec2100-hlg': { for: 'HDR that still looks right on SDR sets — broadcast’s one-signal answer', nm: 'hybrid log-gamma: gamma toe, logarithmic shoulder' },
	'rec2100-linear': { for: 'Rec.2100 in linear light' },
	ipt: { for: 'straight constant-hue lines — gamut mapping without hue drift', nm: 'I intensity · P protan · T tritan' },
	izazbz: { for: 'the intensity-variant of Jzazbz' },
	'hdr-ipt': { for: 'IPT rebuilt for HDR luminance ranges' },
	'hdr-cie-lab': { for: 'Lab rebuilt for HDR — the cube root swapped for a luminance-aware curve' },
	icacb: { for: 'an HDR ΔE space in the ICtCp family' },

	// ── colorimetry & vision ──
	xyz: { for: 'one standard observer for all eyes — color reduced to three integrals', sin: 'imaginary primaries on purpose: nothing you can see sits at X, Y or Z itself', nm: 'chosen so Y alone is luminance; X and Z carry the rest without negative lobes' },
	'xyz-d50': { for: 'XYZ adapted to D50 — the ICC profile connection space' },
	'xyz-abs-d65': { for: 'XYZ carrying absolute luminance in cd/m², for HDR math' },
	xyy: { for: 'chromaticity split from luminance — the space the horseshoe diagram lives in', sin: 'perceptually wildly non-uniform: MacAdam’s ellipses vary 80× across it' },
	lms: { for: 'the cones themselves — long, medium, short — where chromatic adaptation actually happens' },
	uv: { for: 'the chromaticity plane CCT is measured in', nm: 'u,v — later refined to u′,v′ in 1976' },
	kelvin: { for: 'the color of a glowing blackbody as a one-dial space', nm: 'after Lord Kelvin’s absolute temperature scale', sin: 'only the Planckian locus exists — every real white needs a tint offset the scale cannot say' },
	wavelength: { for: 'the spectral colors as a line — the horseshoe’s rim by nanometer', sin: 'no purples: the line between violet and red is not in it' },
	macboyn: { for: 'chromaticity in cone space — vision science’s working diagram', nm: 'the MacLeod–Boynton diagram' },
	dkl: { for: 'the axes LGN neurons actually respond to — cone-opponent, isoluminant', nm: 'named for its three authors' },
	gray: { for: 'luminance alone' },
	dsh: { for: 'colorimetry’s classic triple: dominant wavelength, saturation, brightness — Helmholtz coordinates', sin: 'purples have no dominant wavelength, only a complementary one — the space folds there' },
	rg: { for: 'normalized rg chromaticity — brightness divided out for illumination-robust vision' },
	yrg: { for: 'luma plus rg chromaticity' },

	// ── video & broadcast ──
	ycbcr: { for: 'squeeze color into less bandwidth than luma — the eye forgives chroma blur', sin: 'non-constant luminance: Y′ is built from gamma’d primaries, so luma leaks into chroma at saturated colors', nm: 'the prime on Y′ matters — luma, not luminance' },
	jpeg: { for: 'full-range YCbCr as the still-image workhorse' },
	yuv: { for: 'hide color inside a black-and-white-compatible signal', nm: 'U,V — the analog scaling of B−Y and R−Y' },
	yiq: { for: 'bandwidth shaped to the eye: I gets 1.3 MHz, Q gets 0.4, because orange–cyan acuity beats green–purple', nm: 'in-phase and quadrature of the color subcarrier' },
	ydbdr: { for: 'the French answer — color differences sent one per line' },
	ypbpr: { for: 'analog component video — the three-cable YCbCr' },
	ycgco: { for: 'a lossless, lifting-friendly transform for codecs — two adds and two shifts', nm: 'Cg green difference · Co orange difference' },
	yccbccrc: { for: 'the constant-luminance YCbCr television never adopted', nm: 'the extra c’s read “constant”' },
	xvycc: { for: 'extended-gamut video smuggled through BT.709 negatives', nm: 'extended-video YCC' },
	'smpte-c': { for: 'the phosphors US broadcast actually used, standardized after the fact' },
	photoycc: { for: 'PhotoCD’s scene-referred YCC — film scans with highlight headroom' },

	// ── film & camera ──
	acescg: { for: 'the render/compositing space of the ACES pipeline — linear, wide but real', nm: 'CG = computer graphics; primaries called AP1' },
	acescc: { for: 'pure-log grading space — dials feel like film printer lights', sin: 'pure log has no toe: near-black codes get twitchy' },
	acescct: { for: 'ACEScc with a toe, so lifted blacks grade like film', nm: 'the extra t is the toe' },
	'aces2065-1': { for: 'the archival master — AP0 primaries wrap everything visible', sin: 'AP0 is mostly imaginary: great vault, terrible working space', nm: 'named for its SMPTE standard number, ST 2065-1' },
	acesproxy: { for: 'on-set monitoring log — integer-friendly, never stored' },
	cineon: { for: 'film scans as printing density — the grandfather of every camera log', nm: 'the 10-bit .cin/DPX code values' },
	logc3: { for: 'ALEXA’s scene-referred log — exposure stops spaced evenly', nm: 'Log C: C for Cineon lineage; v3 is the EI-dependent family' },
	logc4: { for: 'ALEXA 35’s 17-stop reboot of Log C', nm: 'the fourth revision' },
	slog: { for: 'Sony’s first cinema log (F35 era)' },
	slog2: { for: 'log for the F65/F55 generation' },
	slog3: { for: 'the Cineon-like revision most Sony cine cameras speak today' },
	vlog: { for: 'VariCam’s log, one curve across sensors' },
	'log3g10': { for: 'REDWideGamutRGB’s companion log', nm: 'log, ×10 gain, 3 stops of headroom above mid-gray at 1.0' },
	'log3g12': { for: 'the wider 12-stop variant' },
	clog: { for: 'Canon’s first log (C300 era)' },
	clog2: { for: 'the full-range grading log' },
	clog3: { for: 'the in-between: more range than C-Log, friendlier than C-Log2' },
	flog: { for: 'Fujifilm’s log for X/GFX video' },
	flog2: { for: 'the 13+ stop revision' },
	nlog: { for: 'Nikon’s log for the Z line' },
	applelog: { for: 'ProRes Log on iPhone 15 Pro — a phone speaking cinema', },
	bmdfilm: { for: 'Blackmagic’s film-look capture log' },
	davinci: { for: 'DaVinci Wide Gamut Intermediate — one grading space for any camera' },
	dlog: { for: 'drone log' },
	tlog: { for: 'DJI’s cinema log (Zenmuse/Inspire)' },
	dcdm: { for: 'the projector’s master format: XYZ with a 2.6 gamma', nm: 'Digital Cinema Distribution Master' },
	erimm: { for: 'extended-range RIMM for scene-referred archives' },
	llog: { for: 'L-Log for Leica video' },
	protune: { for: 'action-camera flat log' },
	milog: { for: 'phone cinema log' },
	olog: { for: 'Osmo’s log profile' },
	redlogfilm: { for: 'Cineon-style legacy RED log' },
	redlog: { for: 'the original RED ONE log' },
	panalog: { for: 'Genesis-era camera log' },
	viperlog: { for: 'the Viper FilmStream camera — raw log that helped start digital cinema' },
	filmicpro: { for: 'the app log that made phones gradeable' },

	// ── appearance models ──
	cam16: { for: 'fix CIECAM02’s numerical failures with one cleaner adaptation transform', sin: 'a full viewing-conditions model: powerful, and overkill anywhere conditions are unknown' },
	'cam16-ucs': { for: 'CAM16 squeezed into a uniform space — modern ΔE work' },
	'cam16-lcd': { for: 'the variant tuned for large differences', nm: 'LCD = large color differences' },
	'cam16-scd': { for: 'the variant tuned for small differences', nm: 'SCD = small color differences' },
	ciecam02: { for: 'the committee appearance model behind ICC v4', sin: 'its CAT02 matrix can go negative for saturated blues — the defect that begat CAM16' },
	'cam02-ucs': { for: 'CIECAM02 as a uniform space — the ΔE workhorse of the 2010s' },
	'cam02-lcd': { for: 'large-difference variant' },
	'cam02-scd': { for: 'small-difference variant' },
	zcam: { for: 'an appearance model born HDR — PQ-based like Jzazbz' },
	hellwig2022: { for: 'CAM16 pruned to what vision data actually supports' },
	rlab: { for: 'Lab with adaptation done right, sized for imaging work', nm: 'refined Lab' },

	// ── print & physical ──
	cmyk: { for: 'process printing’s four plates as a space', sin: 'the naive formula: real separation needs ICC profiles, ink limits and black generation', nm: 'K is the key plate — the one others register to — not “blacK”' },
	cmy: { for: 'subtractive mixing at its simplest — the teaching model' },
	munsell: { for: 'the first perceptual order system — steps an art student can trust', sin: 'defined by the 1943 renotation tables: a lookup with interpolation, not a formula', nm: 'his words “value” and “chroma” are still the field’s vocabulary' },
	'ral-design': { for: 'industrial coatings organized by CIELAB hue–lightness–chroma', nm: 'each code reads H·L·C' },
	coloroid: { for: 'aesthetic spacing for architects — harmony intervals, not ΔE', nm: 'A·T·V: árnyalat, telítettség, világosság — hue, saturation, lightness in Hungarian' },
	ryb: { for: 'the painter’s wheel every kindergarten teaches', sin: 'no standard exists — every RYB implementation mixes differently' },

	// ── specialty & research ──
	cubehelix: { for: 'astronomy colormaps that survive grayscale printing — luminance strictly monotone', nm: 'a helix wound around the gray diagonal of the RGB cube' },
	xyb: { for: 'the codec’s cone-based space — built to hide compression error, not to look at', nm: 'X ≈ L−M opponent · Y luminance-ish · B for blue (S-cone)' },
	osaucs: { for: 'the most uniform lattice ever measured — thirty years of committee judgments', sin: 'no closed-form inverse, and its √2 lattice neighbors make it a dataset more than a picker', nm: 'L·j·g: j is yellowness (jaune), g greenness' },
	tsl: { for: 'skin detection — chromaticity warped so faces cluster tightly', nm: 'tint · saturation · lightness' },
	yes: { for: 'a luma plus two chroma axes used in early face-detection work' },
	ohta: { for: 'segmentation channels that decorrelate natural images with integer-cheap math', nm: 'I1I2I3 in the paper — named for its first author here' },
	lalphabeta: { for: 'the statistics of natural scenes, decorrelated — the engine of Reinhard color transfer', nm: 'l·α·β: log-cone axes' },
}
