// Compile the WASM batch kernel ahead-of-time and inline it as base64.
//
// jz is a BUILD-time dependency only: it compiles wasm/batch.js → a ~4.6 kB wasm
// module, which we embed as base64 in wasm/binary.js so `color-space/wasm` ships a
// portable, zero-runtime-dependency artifact (no fetch, no fs, no compiler).
//
//   npm run build:wasm
//
// Run after changing wasm/batch.js. The conversion formulas there mirror the scalar
// library and are pinned by test/wasm-batch.js.
import { compile } from 'jz'
import { readFileSync, writeFileSync } from 'node:fs'

const src = readFileSync(new URL('../wasm/batch.js', import.meta.url), 'utf8')
const bin = compile(src, { optimize: 'speed' }) // 'speed' = O3: cbrt/pow fast-paths + SIMD
const b64 = Buffer.from(bin).toString('base64')

writeFileSync(
	new URL('../wasm/binary.js', import.meta.url),
	`// Generated by scripts/build-wasm.js (jz @ optimize:'speed'). Do not edit — run \`npm run build:wasm\`.\n` +
	`// ${bin.length} bytes of WASM, base64-inlined for a portable zero-dependency batch kernel.\n` +
	`export default '${b64}'\n`
)
console.log(`wasm/binary.js written — ${bin.length} bytes wasm, ${b64.length} bytes base64`)
