// Compile the WASM batch kernel ahead-of-time. Emits two artifacts from one compile:
//
//   wasm/binary.js        base64-inlined bytes — `color-space/wasm` instantiates these
//                         with zero runtime dependencies (no fetch, no fs, browser-safe).
//   dist/color-space.wasm the same bytes as a real file — for standalone runtimes
//                         (wasmtime, wasmer) and non-JS hosts (Rust/Python/Go).
//
// The kernel imports nothing (own memory, pure math — jz polyfills every transcendental
// in-module), so the same bytes run unchanged in JS AND in standalone runtimes. No wasi
// host lowering: `host:'wasi'` would only matter for runtime services (files, clocks,
// stdio, entropy) this kernel never touches — it just adds a WASI `_initialize` stub and
// ~760 bytes. It's a reactor module (function exports, no `_start`); a host instantiates
// it and calls the conversions directly (e.g. `wasmtime run --invoke rgb_lrgb file 255 128 0`).
//
// `noTailCall` matters for reach: jz tail-calls the PQ encoder's `exp` by default, and the
// tail-call proposal isn't universal (wasmtime yes, wasmer 4.x no). Ordinary frames cost
// one byte and nothing measurable (the batch loops aren't recursive) and run everywhere.
// `maxMemory` declares a growable memory so `alloc()` can grow it for large batches;
// without it the buffer is pinned to one 64 kB page and big batches fault.
//
//   npm run build:wasm
//
// Run after changing wasm/batch.js. The conversion formulas there mirror the scalar
// library and are pinned by test/wasm-batch.js.
import { compile } from 'jz'
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { pathToFileURL } from 'node:url'

// The compile contract — ONE source of truth for the build and test/wasm-standalone.js:
// 'speed' = O3 fast-paths + SIMD; grow to the wasm32 max (4 GB) for large batches;
// noTailCall keeps the bytes valid on runtimes without the tail-call proposal.
export const WASM_OPTS = { optimize: 'speed', maxMemory: 65536, noTailCall: true }
export const wasmSource = () => readFileSync(new URL('../wasm/batch.js', import.meta.url), 'utf8')

// Build only when run directly (`npm run build:wasm`) — importing stays side-effect-free.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
	const bin = compile(wasmSource(), WASM_OPTS)
	const b64 = Buffer.from(bin).toString('base64')

	writeFileSync(
		new URL('../wasm/binary.js', import.meta.url),
		`// Generated by scripts/build-wasm.js (jz @ optimize:'speed'). Do not edit — run \`npm run build:wasm\`.\n` +
		`// ${bin.length} bytes of WASM, base64-inlined for a portable zero-dependency batch kernel.\n` +
		`export default '${b64}'\n`
	)

	mkdirSync(new URL('../dist/', import.meta.url), { recursive: true })
	writeFileSync(new URL('../dist/color-space.wasm', import.meta.url), bin)

	console.log(`wasm/binary.js written — ${bin.length} bytes wasm, ${b64.length} bytes base64`)
	console.log(`dist/color-space.wasm written — ${bin.length} bytes (standalone, import-free)`)
}
