#!/usr/bin/env node
/**
 * Generate types/*.d.ts from the live registry (v3: flat-arg converters, `range`,
 * no min/max/channel/alias). Run: node scripts/generate-types.js
 *
 * The declarations mirror the runtime exactly: `color-space` exports only the
 * default registry + `register` (no named space exports — those never existed at
 * runtime); per-space files type the direct `color-space/<name>.js` imports.
 */
import fs from 'fs'
import path from 'path'
import { execFileSync } from 'node:child_process'
import { fileURLToPath, pathToFileURL } from 'url'
import space from '../index.js'
import lite from '../lite.js'

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..')
const dir = path.join(root, 'types')

const ident = (n) => n.replace(/[^a-zA-Z0-9]/g, '_')
const Iface = (n) => ident(n).replace(/^./, (c) => c.toUpperCase()) + 'Space'
const rangeLit = (r) => r && `[${r.map(([a, b]) => `[${a}, ${b}]`).join(', ')}]`

// space files (spaces/): basename === registered name
const names = fs.readdirSync(path.join(root, 'spaces'))
	.filter((f) => f.endsWith('.js') && space[f.replace(/\.js$/, '')])
	.map((f) => f.replace(/\.js$/, ''))
	.sort()

const banner = '// Generated by scripts/generate-types.js — do not edit by hand\n'

// core interfaces — direct per-space imports are scalar-only; graph hubs add the
// array-like batch overload. Fixed arities let TypeScript catch missing channels.
fs.writeFileSync(path.join(dir, 'color-space.d.ts'), banner + `
/** Trailing parameters used by parameterised spaces (kb/kr, matrices, illuminants). */
export type ConvertParam = number | string | readonly number[];

export interface ScalarConvert1 { (c0: number, ...params: ConvertParam[]): number[]; }
export interface ScalarConvert2 { (c0: number, c1: number, ...params: ConvertParam[]): number[]; }
export interface ScalarConvert3 { (c0: number, c1: number, c2: number, ...params: ConvertParam[]): number[]; }
export interface ScalarConvert4 { (c0: number, c1: number, c2: number, c3: number, ...params: ConvertParam[]): number[]; }
export type ScalarConvert = ScalarConvert1 | ScalarConvert2 | ScalarConvert3 | ScalarConvert4;

export interface Convert1 extends ScalarConvert1 {
	(pixels: ArrayLike<number>, ...params: ConvertParam[]): Float64Array;
	readonly scalar?: ScalarConvert1;
}
export interface Convert2 extends ScalarConvert2 {
	(pixels: ArrayLike<number>, ...params: ConvertParam[]): Float64Array;
	readonly scalar?: ScalarConvert2;
}
export interface Convert3 extends ScalarConvert3 {
	(pixels: ArrayLike<number>, ...params: ConvertParam[]): Float64Array;
	readonly scalar?: ScalarConvert3;
}
export interface Convert4 extends ScalarConvert4 {
	(pixels: ArrayLike<number>, ...params: ConvertParam[]): Float64Array;
	readonly scalar?: ScalarConvert4;
}
/** A conversion with runtime-defined arity (principally custom registered spaces). */
export interface Convert {
	(pixels: ArrayLike<number>, ...params: ConvertParam[]): Float64Array;
	(...channelsAndParams: ConvertParam[]): number[];
	readonly scalar?: (...args: ConvertParam[]) => number[];
}

/** A color-space definition. Graph-wired conversion methods are added by a hub. */
export interface ColorSpace<Name extends string = string> {
	readonly name: Name;
	readonly range: ReadonlyArray<readonly [number, number]>;
	/** Custom definitions may declare converters keyed by a neighbouring space id. */
	[key: string]: unknown;
}
`)

const arityType = (n, scalar = false) => `${scalar ? 'Scalar' : ''}Convert${space[n].range.length}`
const directMethods = (n) => {
	const url = pathToFileURL(path.join(root, 'spaces', n + '.js')).href
	const code = `import s from ${JSON.stringify(url)}; console.log(JSON.stringify(Object.keys(s).filter(k => typeof s[k] === 'function')))`
	return JSON.parse(execFileSync(process.execPath, ['--input-type=module', '--eval', code], { encoding: 'utf8' }))
		.filter((k) => names.includes(k)).sort()
}

// per-space direct imports: only methods that exist when that module is imported
// alone (natural neighbours / deliberate rgb conveniences), never graph-wired lies.
for (const n of names) {
	const range = space[n].range, methods = directMethods(n)
	fs.writeFileSync(path.join(dir, n + '.d.ts'), banner + `import { ColorSpace, ${arityType(n, true)} } from './color-space.js';

export interface ${Iface(n)} extends ColorSpace<'${n}'> {
	readonly name: '${n}';${range ? `\n\treadonly range: ${rangeLit(range)};` : ''}${methods.map((m) => `\n\treadonly '${m}': ${arityType(n, true)};`).join('')}
}

declare const ${ident(n)}: ${Iface(n)};
export default ${ident(n)};
`)
}

const union = (xs) => xs.length ? xs.map((n) => `'${n}'`).join(' | ') : 'never'
// registry barrel: known ids are exact (typos fail); register() returns an extended
// type when callers keep its return value.
const barrel = (spaceNames, unionName, setDoc) => {
	const byArity = [1, 2, 3, 4].map((a) => spaceNames.filter((n) => space[n].range.length === a))
	return banner +
	`import { ColorSpace, Convert, ConvertParam, Convert1, Convert2, Convert3, Convert4, ScalarConvert1, ScalarConvert2, ScalarConvert3, ScalarConvert4 } from './color-space.js';\n\n` +
	`export { ColorSpace, Convert, ConvertParam, Convert1, Convert2, Convert3, Convert4, ScalarConvert1, ScalarConvert2, ScalarConvert3, ScalarConvert4 };\n\n` +
	`/** Every built-in space id. */\nexport type ${unionName} =\n\t${spaceNames.map((n) => `'${n}'`).join(' |\n\t')};\n\n` +
	`type ConvertFor<N extends ${unionName}> = N extends ${union(byArity[0])} ? Convert1 : N extends ${union(byArity[1])} ? Convert2 : N extends ${union(byArity[2])} ? Convert3 : Convert4;\n` +
	`type ScalarFor<N extends ${unionName}> = N extends ${union(byArity[0])} ? ScalarConvert1 : N extends ${union(byArity[1])} ? ScalarConvert2 : N extends ${union(byArity[2])} ? ScalarConvert3 : ScalarConvert4;\n` +
	`export type RegisteredSpace<N extends ${unionName}> = ColorSpace<N> & { readonly [T in ${unionName}]: ConvertFor<N> };\n` +
	`export type SpaceRegistry = { readonly [K in ${unionName}]: RegisteredSpace<K> };\n\n` +
	`/** ${setDoc} */\ndeclare const space: SpaceRegistry;\nexport default space;\n\n` +
	`/** Existing→new primitive edges, paired with methods on the new space for new→existing. */\nexport type ReverseConversions = Partial<{ [K in ${unionName}]: ScalarFor<K> }>;\n` +
	`/** Register a copied custom space with edges in both directions; the returned registry remains any-to-any. */\nexport function register<N extends string, S extends ColorSpace<N>>(newSpace: S, from: ReverseConversions): SpaceRegistry & Record<N, S & { readonly [T in ${unionName}]: Convert }>;\n`
}

fs.writeFileSync(path.join(dir, 'index.d.ts'),
	barrel(names, 'SpaceName', 'All registered color spaces, keyed by name; every pair (identity included) converts.'))

// lite barrel — the compact hub (wasm-covered spaces, plain JS)
const liteNames = names.filter((n) => lite[n])
fs.writeFileSync(path.join(dir, 'lite.d.ts'),
	barrel(liteNames, 'LiteSpaceName', 'The compact space set (mirrors color-space/wasm coverage), keyed by name.'))

// hub — the wiring machinery behind the registries
fs.writeFileSync(path.join(dir, 'hub.d.ts'), banner + `import { ColorSpace } from './color-space.js';

export type Hub = { [name: string]: ColorSpace };
/** Build a registry from a list of spaces (shallow-copied in) and wire the conversion graph. */
export function createHub(spaces: readonly ColorSpace[]): Hub;
/** (Re)wire every reachable conversion, identity included. */
export function wire(space: Hub): void;
/** Validate a new definition's id, range, uniqueness and outgoing connectivity. */
export function validate(space: Hub, s: ColorSpace): void;
/** Register a copied definition plus existing→new edges, preserving an any-to-any graph. */
export function registerSpace(space: Hub, s: ColorSpace, from: { [name: string]: (...channels: number[]) => number[] }): Hub;
`)

// wasm — the prebuilt kernel over the lite space set
fs.writeFileSync(path.join(dir, 'wasm.d.ts'), banner + `import { LiteSpaceName } from './lite.js';
export { LiteSpaceName };

export const spaces: readonly LiteSpaceName[];
export function alloc(n: number): Float64Array;
export function convert(from: LiteSpaceName, to: LiteSpaceName, n: number): void;
/** Float64 input defaults in place; other array-likes return a new Float64Array. */
export function convertBatch(from: LiteSpaceName, to: LiteSpaceName, src: ArrayLike<number>, dst?: Float64Array, n?: number): Float64Array;

export interface WasmConvert {
	(c0: number, c1: number, c2: number): number[];
	(pixels: ArrayLike<number>): Float64Array;
}
declare const api: {
	readonly [K in LiteSpaceName]: { readonly name: K } & { readonly [T in LiteSpaceName]: WasmConvert };
};
export default api;
`)
fs.writeFileSync(path.join(dir, 'wasm-spaces.d.ts'), banner + `import { LiteSpaceName } from './lite.js';
export const spaces: readonly LiteSpaceName[];
export default spaces;
`)

// gl — exact declarations for the lean composer, full registry, translator and chunks
const glShared = `
export interface GlLut { name: string; w: number; h: number; data(): Float32Array; }
export interface GlChunk {
	readonly name: string;
	readonly deps?: readonly GlChunk[];
	readonly requires?: readonly string[];
	readonly dim?: 1 | 2 | 3 | 4;
	readonly edges: Readonly<Record<string, readonly [string | null, string | null]>>;
	readonly code: string;
	readonly tol?: number;
	readonly lut?: GlLut;
}
export interface GlStep { readonly fn: string; readonly chunk: GlChunk; }
export type GlGraph = Readonly<Record<string, Readonly<Record<string, GlStep>>>>;
export type GlEnd = string | GlChunk;
export type GlPairs = readonly (readonly [GlEnd, GlEnd])[];
export interface GlComposer {
	readonly chunks: Readonly<Record<string, GlChunk>>;
	readonly graph: GlGraph;
	readonly luts: Readonly<Record<string, GlLut>>;
	glsl(chunk: GlChunk): string;
	glsl(from: GlEnd, to: GlEnd): string;
	glsl(pairs: GlPairs): string;
}
`
fs.writeFileSync(path.join(dir, 'gl.d.ts'), banner + glShared + `
export function compose(list?: readonly GlChunk[]): GlComposer;
export function glsl(chunk: GlChunk): string;
export function glsl(from: GlEnd, to: GlEnd): string;
export function glsl(pairs: GlPairs): string;
export function wgsl(chunk: GlChunk): string;
export function wgsl(from: GlEnd, to: GlEnd): string;
export function wgsl(pairs: GlPairs): string;
export default glsl;
`)
fs.writeFileSync(path.join(dir, 'gl-all.d.ts'), banner + `import { GlChunk, GlGraph, GlLut } from './gl.js';
export const chunks: Readonly<Record<string, GlChunk>>;
export const graph: GlGraph;
export const luts: Readonly<Record<string, GlLut>>;
export const spaces: readonly string[];
export function glsl(from: string, to: string): string;
export function glsl(pairs: readonly (readonly [string, string])[]): string;
export default glsl;
`)
fs.writeFileSync(path.join(dir, 'gl-translate.d.ts'), banner + `/** Translate the library's restricted GLSL dialect to WGSL. */
export function translate(glsl: string): string;
`)
fs.writeFileSync(path.join(dir, 'gl-wgsl.d.ts'), banner + `export { translate } from './gl-translate.js';
export function wgsl(from: string, to: string): string;
export default wgsl;
`)
fs.writeFileSync(path.join(dir, 'gl-chunk.d.ts'), banner + `import { GlChunk } from './gl.js';
declare const chunk: GlChunk;
export default chunk;
`)
fs.writeFileSync(path.join(dir, 'gl-util.d.ts'), banner + `export interface GlHelper { readonly name: string; readonly code: string; }
declare const helpers: readonly GlHelper[];
export default helpers;
`)

// whitepoints & gamuts — plain data tables
fs.writeFileSync(path.join(dir, 'whitepoints.d.ts'), banner + `
/** CIE standard illuminant whitepoints, [X, Y=100, Z], keyed by observer (2/10) then illuminant. */
declare const whitepoint: {
	2: { [illuminant: string]: [number, number, number] };
	10: { [illuminant: string]: [number, number, number] };
};
export default whitepoint;
export { whitepoint };
`)
fs.writeFileSync(path.join(dir, 'gamuts.d.ts'), banner + `
/** RGB working-space gamuts: primary chromaticities + white point name. */
declare const gamut: {
	[space: string]: {
		primaries: { r: [number, number]; g: [number, number]; b: [number, number] };
		white: string;
	};
};
export default gamut;
export { gamut };
`)

// numeric primitives
fs.writeFileSync(path.join(dir, 'util.d.ts'), banner + `
export function mat3(m: readonly number[], x: number, y: number, z: number): [number, number, number];
export function inv3(m: readonly number[]): number[];
export function spow(a: number, b: number): number;
export function cartToPolar(l: number, a: number, b: number, threshold?: number): [number, number, number];
export function polarToCart(l: number, c: number, h: number): [number, number, number];
`)
fs.writeFileSync(path.join(dir, 'transfers.d.ts'), banner + `
export function srgbToLinear(v: number): number;
export function linearToSrgb(v: number): number;
export function gammaDecode(v: number, gamma: number): number;
export function gammaEncode(v: number, gamma: number): number;
export function bt2020Decode(v: number): number;
export function bt2020Encode(v: number): number;
export function bt709Decode(v: number): number;
export function bt709Encode(v: number): number;
export function smpte240mDecode(v: number): number;
export function smpte240mEncode(v: number): number;
export function pqST2084Decode(v: number): number;
export function pqST2084Encode(v: number): number;
`)
fs.writeFileSync(path.join(dir, 'cie.d.ts'), banner + `
export const ε: number;
export const κ: number;
export const ε3: number;
export function labF(t: number): number;
export function labFInv(t: number): number;
`)
fs.writeFileSync(path.join(dir, 'mcp.d.ts'), banner + `
export interface McpMessage { jsonrpc?: '2.0'; id?: string | number | null; method?: string; params?: unknown; }
/** Handle one JSON-RPC message, writing any response to stdout. */
export function handle(message: McpMessage): void;
`)

// lut — the .cube exporter (lut.js takes space objects, so it types against ColorSpace)
fs.writeFileSync(path.join(dir, 'lut.d.ts'), banner + `import { ColorSpace } from './color-space.js';

/** A sampled conversion lattice: 0–1-normalized output triples (3D is red-fastest). */
export interface LutTable {
	from: ColorSpace;
	to: ColorSpace;
	dims: 1 | 3;
	size: number;
	domain: ReadonlyArray<readonly [number, number]>;
	range: ReadonlyArray<readonly [number, number]>;
	data: Float64Array;
	/** Resolve-flavor combined cube: the per-channel 1D tone shaper applied before the 3D lattice */
	shaper?: Float64Array;
	shaperSize?: number;
}

/** Off-lattice deviation vs the direct conversion, as fractions of the target's full scale. */
export interface LutStats {
	max: number;
	median: number;
	n: number;
	/** over samples whose direct result lands inside the target range — the LUT's working set; n is the count actually collected */
	in: { max: number; median: number; share: number; n: number };
}

/** Is the conversion purely per-channel (a transfer curve, no cross-channel term)? */
export function channelwise(from: ColorSpace, to: ColorSpace): boolean;

/** Sample a conversion into a LUT lattice. */
export function table(from: ColorSpace, to: ColorSpace, opts?: { size?: number; dims?: 1 | 3; shaper?: boolean | number }): LutTable;

/** Read one color through the lattice (linear/trilinear), native units on both ends. */
export function apply(tab: LutTable, vals: number[]): number[];

/** Measure the lattice against the direct conversion at random off-lattice points. */
export function verify(tab: LutTable, n?: number): LutStats;

/** Render a conversion as a .cube file (Resolve, Premiere, Final Cut, OBS, ffmpeg; shaper → Resolve/OCIO flavor). */
export function cube(from: ColorSpace, to: ColorSpace, opts?: { size?: number; dims?: 1 | 3; shaper?: boolean | number; title?: string; verify?: number | false }): string;
`)

// icc — matrix+TRC where honest, bounded CLUT otherwise
fs.writeFileSync(path.join(dir, 'icc.d.ts'), banner + `import { ColorSpace } from './color-space.js';

export interface IccOptions {
	description?: string;
	/** Wired XYZ space; enables reverse CLUTs when the source has a continuous inverse. */
	xyz?: ColorSpace<'xyz'>;
	grid?: number;
	bgrid?: number;
	samples?: number;
	date?: readonly [number, number, number, number, number, number];
}
export interface IccClut {
	sig: string; cls: 'spac' | 'scnr'; nin: number; grid: number; bgrid: number;
	a2b: Uint16Array; b2a: Uint16Array | null;
}
export function colorants(s: ColorSpace, samples?: number): {
	rXYZ: [number, number, number]; gXYZ: [number, number, number]; bXYZ: [number, number, number];
	trc: Float64Array | null; chad: number[];
};
export function clut(s: ColorSpace, opts?: IccOptions): IccClut;
export function kind(s: ColorSpace, opts?: Pick<IccOptions, 'xyz'>): 'mntr' | 'spac' | 'scnr' | null;
/** Render any honestly representable bounded space as an ICC v2 profile. */
export function profile(s: ColorSpace, opts?: IccOptions): Uint8Array;
`)

// remove stale: wrong-extension .ts and orphans without a .js
const KEEP = [
	'color-space.d.ts', 'index.d.ts', 'lite.d.ts', 'hub.d.ts', 'wasm.d.ts', 'wasm-spaces.d.ts',
	'gl.d.ts', 'gl-all.d.ts', 'gl-wgsl.d.ts', 'gl-translate.d.ts', 'gl-chunk.d.ts', 'gl-util.d.ts',
	'whitepoints.d.ts', 'gamuts.d.ts', 'util.d.ts', 'transfers.d.ts', 'cie.d.ts', 'mcp.d.ts', 'lut.d.ts', 'icc.d.ts',
]
for (const f of fs.readdirSync(dir)) {
	if (f.endsWith('.ts') && !f.endsWith('.d.ts')) fs.unlinkSync(path.join(dir, f)) // lrgb.ts, xvycc.ts, …
	else if (f.endsWith('.d.ts') && !KEEP.includes(f)) {
		const base = f.replace(/\.d\.ts$/, '')
		if (!names.includes(base)) { fs.unlinkSync(path.join(dir, f)); console.log('removed stale', f) }
	}
}

console.log(`generated ${names.length} space d.ts + exact hub/wasm/gl/lut/icc/tool declarations`)
