#!/usr/bin/env node
/**
 * Generate types/*.d.ts from the live registry (v3: flat-arg converters, `range`,
 * no min/max/channel/alias). Run: node scripts/generate-types.js
 */
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import space from '../index.js'

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..')
const dir = path.join(root, 'types')

const ident = (n) => n.replace(/[^a-zA-Z0-9]/g, '_')
const Iface = (n) => ident(n).replace(/^./, (c) => c.toUpperCase()) + 'Space'
const rangeLit = (r) => r && `[${r.map(([a, b]) => `[${a}, ${b}]`).join(', ')}]`

// space files: basename === registered name
const names = fs.readdirSync(root)
	.filter((f) => f.endsWith('.js') && f !== 'index.js' && space[f.replace(/\.js$/, '')])
	.map((f) => f.replace(/\.js$/, ''))
	.sort()

const banner = '// Generated by scripts/generate-types.js — do not edit by hand\n'

// core interface
fs.writeFileSync(path.join(dir, 'color-space.d.ts'), banner + `
/** Convert one space's channel values to another space: e.g. \`rgb.lab(255, 0, 0)\`. */
export type Convert = (...channels: number[]) => number[];

/** A color space: its id, conventional channel \`range\`, and converters to every other space. */
export interface ColorSpace {
	/** space id, e.g. 'rgb' */
	name: string;
	/** conventional channel ranges, e.g. [[0, 255], [0, 255], [0, 255]] */
	range?: ReadonlyArray<readonly [number, number]>;
	/** converter to another space, keyed by its name — \`space.rgb.lab(255, 0, 0)\` */
	[to: string]: any;
}
`)

// per-space
for (const n of names) {
	const range = space[n].range
	fs.writeFileSync(path.join(dir, n + '.d.ts'), banner + `import { ColorSpace } from './color-space';

export interface ${Iface(n)} extends ColorSpace {
	name: '${n}';${range ? `\n\trange: ${rangeLit(range)};` : ''}
}

declare const ${ident(n)}: ${Iface(n)};
export default ${ident(n)};
`)
}

// barrel
fs.writeFileSync(path.join(dir, 'index.d.ts'), banner +
	`import { ColorSpace, Convert } from './color-space';\n` +
	names.map((n) => `import ${ident(n)} from './${n}';`).join('\n') + '\n\n' +
	`export { ColorSpace, Convert };\n` +
	`export { ${names.map(ident).join(', ')} };\n\n` +
	`/** All registered color spaces, keyed by name. */\ndeclare const space: { [name: string]: ColorSpace };\nexport default space;\n\n` +
	`/** Register a custom space and wire conversions to/from every existing space. */\nexport function register(newSpace: ColorSpace): { [name: string]: ColorSpace };\n`)

// util
fs.writeFileSync(path.join(dir, 'util.d.ts'), banner +
	`/** 3×3 matrix (row-major, 9 elements) times a 3-vector. */\nexport declare const mat3: (m: number[], x: number, y: number, z: number) => [number, number, number];\n`)

// remove stale: wrong-extension .ts and orphans without a .js
for (const f of fs.readdirSync(dir)) {
	if (f.endsWith('.ts') && !f.endsWith('.d.ts')) fs.unlinkSync(path.join(dir, f)) // lrgb.ts, xvycc.ts, …
	else if (f.endsWith('.d.ts') && !['color-space.d.ts', 'index.d.ts', 'util.d.ts'].includes(f)) {
		const base = f.replace(/\.d\.ts$/, '')
		if (!names.includes(base)) { fs.unlinkSync(path.join(dir, f)); console.log('removed stale', f) }
	}
}

console.log(`generated ${names.length} space d.ts + core/index/util`)
