#!/usr/bin/env node
/**
 * Generate types/*.d.ts from the live registry (v3: flat-arg converters, `range`,
 * no min/max/channel/alias). Run: node scripts/generate-types.js
 */
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import space from '../index.js'
import lite from '../lite.js'

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..')
const dir = path.join(root, 'types')

const ident = (n) => n.replace(/[^a-zA-Z0-9]/g, '_')
const Iface = (n) => ident(n).replace(/^./, (c) => c.toUpperCase()) + 'Space'
const rangeLit = (r) => r && `[${r.map(([a, b]) => `[${a}, ${b}]`).join(', ')}]`

// space files: basename === registered name
const names = fs.readdirSync(root)
	.filter((f) => f.endsWith('.js') && f !== 'index.js' && space[f.replace(/\.js$/, '')])
	.map((f) => f.replace(/\.js$/, ''))
	.sort()

const banner = '// Generated by scripts/generate-types.js — do not edit by hand\n'

// core interface
fs.writeFileSync(path.join(dir, 'color-space.d.ts'), banner + `
/**
 * Convert one space's values to another space, in either calling form:
 * scalar — \`rgb.lab(255, 0, 0)\` → \`number[]\`; batch — an interleaved
 * array-like of pixels (stride = the space's channel count) → a new
 * \`Float64Array\`: \`rgb.lab([255, 0, 0, 0, 128, 255])\`. Trailing params
 * (e.g. ycbcr's kb, kr) follow the channels / the pixel array.
 */
export type Convert = {
	(...channels: number[]): number[];
	(pixels: ArrayLike<number>, ...params: number[]): Float64Array;
};

/** A color space: its id, conventional channel \`range\`, and converters to every other space. */
export interface ColorSpace {
	/** space id, e.g. 'rgb' */
	name: string;
	/** conventional channel ranges, e.g. [[0, 255], [0, 255], [0, 255]] */
	range?: ReadonlyArray<readonly [number, number]>;
	/** converter to another space, keyed by its name — \`space.rgb.lab(255, 0, 0)\` */
	[to: string]: any;
}
`)

// per-space
for (const n of names) {
	const range = space[n].range
	fs.writeFileSync(path.join(dir, n + '.d.ts'), banner + `import { ColorSpace } from './color-space';

export interface ${Iface(n)} extends ColorSpace {
	name: '${n}';${range ? `\n\trange: ${rangeLit(range)};` : ''}
}

declare const ${ident(n)}: ${Iface(n)};
export default ${ident(n)};
`)
}

// barrel
fs.writeFileSync(path.join(dir, 'index.d.ts'), banner +
	`import { ColorSpace, Convert } from './color-space';\n` +
	names.map((n) => `import ${ident(n)} from './${n}';`).join('\n') + '\n\n' +
	`export { ColorSpace, Convert };\n` +
	`export { ${names.map(ident).join(', ')} };\n\n` +
	`/** All registered color spaces, keyed by name. */\ndeclare const space: { [name: string]: ColorSpace };\nexport default space;\n\n` +
	`/** Register a custom space and wire conversions to/from every existing space. */\nexport function register(newSpace: ColorSpace): { [name: string]: ColorSpace };\n`)

// lite barrel — the compact hub (wasm-covered spaces, plain JS)
const liteNames = names.filter((n) => lite[n])
fs.writeFileSync(path.join(dir, 'lite.d.ts'), banner +
	`import { ColorSpace, Convert } from './color-space';\n` +
	liteNames.map((n) => `import ${ident(n)} from './${n}';`).join('\n') + '\n\n' +
	`export { ColorSpace, Convert };\n` +
	`export { ${liteNames.map(ident).join(', ')} };\n\n` +
	`/** The compact space set (mirrors color-space/wasm coverage), keyed by name. */\ndeclare const space: { [name: string]: ColorSpace };\nexport default space;\n\n` +
	`/** Register a custom space and wire conversions to/from every existing space. */\nexport function register(newSpace: ColorSpace): { [name: string]: ColorSpace };\n`)

// util
fs.writeFileSync(path.join(dir, 'util.d.ts'), banner +
	`/** 3×3 matrix (row-major, 9 elements) times a 3-vector. */\nexport declare const mat3: (m: number[], x: number, y: number, z: number) => [number, number, number];\n`)

// lut — the .cube exporter (lut.js takes space objects, so it types against ColorSpace)
fs.writeFileSync(path.join(dir, 'lut.d.ts'), banner + `import { ColorSpace } from './color-space';

/** A sampled conversion lattice: 0–1-normalized output triples (3D is red-fastest). */
export interface LutTable {
	from: ColorSpace;
	to: ColorSpace;
	dims: 1 | 3;
	size: number;
	domain: ReadonlyArray<readonly [number, number]>;
	range: ReadonlyArray<readonly [number, number]>;
	data: Float64Array;
}

/** Off-lattice deviation vs the direct conversion, as fractions of the target's full scale. */
export interface LutStats {
	max: number;
	median: number;
	n: number;
	/** over samples whose direct result lands inside the target range — the LUT's working set; n is the count actually collected */
	in: { max: number; median: number; share: number; n: number };
}

/** Is the conversion purely per-channel (a transfer curve, no cross-channel term)? */
export function channelwise(from: ColorSpace, to: ColorSpace): boolean;

/** Sample a conversion into a LUT lattice. */
export function table(from: ColorSpace, to: ColorSpace, opts?: { size?: number; dims?: 1 | 3 }): LutTable;

/** Read one color through the lattice (linear/trilinear), native units on both ends. */
export function apply(tab: LutTable, vals: number[]): number[];

/** Measure the lattice against the direct conversion at random off-lattice points. */
export function verify(tab: LutTable, n?: number): LutStats;

/** Render a conversion as a .cube file (Resolve, Premiere, Final Cut, OBS, ffmpeg). */
export function cube(from: ColorSpace, to: ColorSpace, opts?: { size?: number; dims?: 1 | 3; title?: string; verify?: number | false }): string;
`)

// remove stale: wrong-extension .ts and orphans without a .js
for (const f of fs.readdirSync(dir)) {
	if (f.endsWith('.ts') && !f.endsWith('.d.ts')) fs.unlinkSync(path.join(dir, f)) // lrgb.ts, xvycc.ts, …
	else if (f.endsWith('.d.ts') && !['color-space.d.ts', 'index.d.ts', 'lite.d.ts', 'util.d.ts', 'lut.d.ts'].includes(f)) {
		const base = f.replace(/\.d\.ts$/, '')
		if (!names.includes(base)) { fs.unlinkSync(path.join(dir, f)); console.log('removed stale', f) }
	}
}

console.log(`generated ${names.length} space d.ts + core/index/util`)
